name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # - name: Generate stats SVG
      #   run: |
      #     mkdir -p assets
      #     curl -s "https://github-readme-stats.vercel.app/api?username=anubhav1772&show_icons=true&theme=transparent" \
      #       -o assets/stats.svg
            
      - name: Generate stats SVG
        run: |
          mkdir -p assets
      
          curl -sL \
            "https://github-readme-stats.vercel.app/api?username=anubhav1772&show_icons=true&theme=transparent&cache_seconds=21600" \
            -o assets/stats.svg
      
          # Validate SVG
          if ! grep -q "<svg" assets/stats.svg; then
            echo "Invalid SVG generated:"
            head -n 20 assets/stats.svg
            exit 1
          fi

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add assets/stats.svg
          git diff --cached --quiet || git commit -m "Update GitHub stats"
          git push
